#Imports

In [52]:
import numpy as np
from scipy import stats
import statsmodels.api as sm
from scipy import random
import matplotlib.pyplot as plt

#Implementation of Linear Congruential Algorithm

In [1]:
""" x is seed.
a,b,m are the parameters ansd l is the lenght of sample."""
def lcg(x, a, b, m, l):
  temp =[]
  for i in range(l):
    x = (a * x + b) % m
    temp.append(x)
  return np.array(temp)

In [ ]:
#Example
lcg(1, 947,3937,5241, 10)


array([4884, 1282, 2079, 2134, 1809, 3253, 2820, 1567, 4683, 4852])

# Shuffling pseudo random vector generation using congruential elements

In [3]:
# array is a 1D vector and rand is a random integer less that len(array).
def Shuff(array, rand):
  temp = array.copy()
  temp[0] = array[rand]
  temp[rand] = array[0]
  return temp

In [6]:
#Example
Shuff(np.arange(12), 3)

array([ 3,  1,  2,  0,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
# Shuffling demanded congruential vector with length 100, 109 and 500 examples
Sh_100 = Shuff(lcg(1, 947,3937,5241, 100), np.random.randint(0, 100))
Sh_109 = Shuff(lcg(1, 947,3937,5241, 109), np.random.randint(0, 109))
Sh_500 = Shuff(lcg(1, 947,3937,5241, 500), np.random.randint(0, 500))

#Comparisons

Comparison of execution time for generation of three 5000 sample vectors from a 100, 109 and 500 unit vectors respectively

In [77]:
%%time
S_100=[Shuff(lcg(1, 947,3937,5241, 100), np.random.randint(0, 100)) for i in range(5000)]

CPU times: user 276 ms, sys: 20.8 ms, total: 297 ms
Wall time: 266 ms


In [78]:
%%time
S_109 = [Shuff(lcg(1, 947,3937,5241, 109), np.random.randint(0, 109)) for i in range(5000)]

CPU times: user 294 ms, sys: 26.7 ms, total: 320 ms
Wall time: 290 ms


In [79]:
%%time
S_500 = [Shuff(lcg(1, 947,3937,5241, 500), np.random.randint(0, 500)) for i in range(5000)]

CPU times: user 986 ms, sys: 50.2 ms, total: 1.04 s
Wall time: 962 ms


In [25]:
S_100 = [Shuff(lcg(1, 947,3937,5241, 100), np.random.randint(0, 100)) for i in range(5000)]
S_109 = [Shuff(lcg(1, 947,3937,5241, 109), np.random.randint(0, 109)) for i in range(5000)]
S_500 = [Shuff(lcg(1, 947,3937,5241, 500), np.random.randint(0, 500)) for i in range(5000)]

S_100 = np.array(S_100)
S_109 = np.array(S_109)
S_500 = np.array(S_500)

KS test for uniformality of S_100, S_109 and S-500

In [26]:
# Making 1D arrays
S_100 = S_100.reshape(S_100.shape[0]*S_100.shape[1])
S_109 = S_109.reshape(S_109.shape[0]*S_109.shape[1])
S_500 = S_500.reshape(S_500.shape[0]*S_500.shape[1])

In [27]:
#Normalization
t= S_100.min()
s= S_100.max()- S_100.min()
S_100=(S_100-t)/s
#__________________________

St_109= S_109.min()
s= S_109.max()- S_109.min()
S_109=(S_109-t)/s
#__________________________

t= S_500.min()
s= S_500.max()- S_500.min()
S_500=(S_500-t)/s

In [30]:
stats.kstest(S_100, 'uniform')

KstestResult(statistic=0.06548726243429037, pvalue=0.0)

In [31]:
stats.kstest(S_109, 'uniform')

KstestResult(statistic=0.06170309062647228, pvalue=0.0)

In [32]:
stats.kstest(S_500, 'uniform')

KstestResult(statistic=0.04679205652090895, pvalue=0.0)

**Correlations**

In [39]:
Corr_100 = np.correlate(S_100,S_100,  mode='full')
Corr_109 = np.correlate(S_109,S_109,  mode='full')
Corr_500 = np.correlate(S_500,S_500,  mode='full')

In [48]:
t= Sh_500.min()
s= Sh_500.max()- Sh_500.min()
Sh_500=(Sh_500-t)/s

In [49]:
np.correlate(Sh_500,Sh_500,  mode='full')

array([  0.50712748,   0.54915887,   0.53159648,   0.84523562,
         1.11403448,   1.47608662,   1.6278621 ,   1.90860127,
         2.59971916,   3.15702361,   3.19040016,   3.07216363,
         4.21190634,   4.96959783,   4.39594403,   5.18312641,
         5.34478592,   5.40742468,   5.61364841,   5.71838112,
         6.36760745,   6.58893628,   6.04130745,   6.61359281,
         7.26486455,   7.19386131,   7.06765105,   8.28487453,
         7.8187033 ,   7.99288544,   9.31639873,   8.64211447,
         9.87840084,   9.75170065,   9.40797823,   9.45024739,
        10.6787909 ,  10.18416141,  11.18608891,  11.88793612,
        11.57276822,  11.6132602 ,  12.25746691,  12.2574874 ,
        14.02072743,  14.42015832,  13.47195647,  14.43930175,
        14.27565837,  15.03843253,  14.89108479,  16.04759961,
        15.70868596,  17.02136   ,  15.61487687,  15.89372588,
        16.94975434,  17.02887654,  17.33710953,  18.40008001,
        16.99718677,  18.06118004,  17.57099871,  18.28

In [41]:
Corr_100.mean()

67446.65680664965

In [42]:
Corr_109.mean()

73492.17311432045

In [43]:
Corr_500.mean()

334210.29161406466

#Montecarlo Integral Simulation

In [72]:
a=-10000
b= -1.645
N = 10000
xrand=np.zeros(N)
for i in range(len(xrand)):
  xrand[i]=random.uniform(a, b)


def gaussian(x):
  return (1/(np.sqrt(2*np.pi)))*np.exp(-0.5*(x**2))

integral=0
for i in range(N):
  integral+= gaussian(xrand[i])
answer= (b-a)/float(N)*integral      

In [73]:
answer


1.010974175897704

In [ ]:
#In order to calculation of z_0,05, we run the above simulation for different 'b' values till the simulation answer get close to the 0.05.  

In [67]:
a=-10000
b= 10000
N = 10000


def gaussian(x):
  return (1/(np.sqrt(2*np.pi)))*np.exp(-0.5*(x**2))
def Montecarlo(a, b, n):
  xrand=np.zeros(N)
  for i in range(len(xrand)):
    xrand[i]=random.uniform(a, b)

  integral=0
  for i in range(N):
    integral+= gaussian(xrand[i])
  return (b-a)/float(N)*integral      

In [76]:
Resolution = np.linspace(0,10, 10000)
for i in Resolution:
  if abs(Montecarlo(-10000,i,10000)-0.05)<0.001:
    print(i)

-1.825465012
